#!/usr/bin/env bash
# d

[ -z "$1" ] && {
	printf "d filename.cpp\n"
	exit 1
}

INPUT="$(xclip -selection primary -o || xclip -selection clipboard -o)"

printf "BEGIN INPUT\n$INPUT\nEND INPUT\n\n"

g++ -std=c++17 "$1" -Wall -DDEBUG && printf "$INPUT\n" | (time ./a.out)

## g++ "$1" -Wall -DDEBUG && cat ./in | (time ./a.out)

