#!/usr/bin/env bash
# d

[ -z "$1" ] && {
	printf "d filename.cpp\n"
	exit 1
}

# bash
g++ "$1" -Wall -DDEBUG && cat ./in | (time ./a.out)
 
# zsh
#g++ "$1" -Wall -DDEBUG && { cat ./in | time ./a.out }


