#!/usr/bin/env bash
# p
 
[ -z "$1" ] && {
	printf "p filename.cpp\n"
	exit 1
}

INPUT="$(xclip -selection primary -o || xclip -selection clipboard -o)"

printf "BEGIN INPUT\n$INPUT\nEND INPUT\n\n"

g++ -std=c++17 "$1" -Wall -DPROD && printf "$INPUT\n" | (time ./a.out)

## g++ "$1" -Wall -DPROD && cat ./in | (time ./a.out)

